site_name: Unit 1
site_url: https://www.learnpytorch.io
site_description: Seminar Presentation Notes

# repo_url: https://github.com/yehzx/{repo}
# repo_name: yehzx/{repo}

theme:
  name: material
  highlightjs: true
  features:
    - navigation.instant
    - navigation.top
  palette:
    primary: black

markdown_extensions:
  - pymdownx.tilde
  - pymdownx.betterem
  - attr_list
  - md_in_html

plugins:
  - search
  - glightbox

nav:
  - Home: 'index.md'
  - Epigenetic dynamics:
    - Background knowledge: '1_background.md'
    - Introduction: '1_introduction.md'
    - Results and Discussion: '1_results_discussion.md'
  - Heterochromatin and RNAi:
    - Background knowledge: '2_background.md'
    - Introduction: '2_introduction.md'
    - Results and Discussion: '2_results_discussion.md'
